### ISSUE TITLE
Test/Debug September Staging Server

### ISSUE THREAD

**Issue by Tthomas63** [codalab/chalab#66]
Currently I have setup a Heroku server with the progress on all `p1` issues.

URL: https://chalab.herokuapp.com/
# Known issues

- [x] Documentation: ~~Have custom template tags auto-render. Currently have to click edit, update initially for them to display right.~~ Patched

- [ ] Login/Sign-up form errors have broken template tags. 

- [x] ~~Debug Logic Coupled with Email Verification: No need to confirm email~~ Should be working as expected

- [x] ~~Download from home does not work unless you rebuild twice. This is due to getting multiple bundles back per Challenge, and trying to only return the latest.~~ Patched

- [x] ~~Baseline download URL currently appends the current domain name, and the link to the azure blob location.~~ Patched 

- [x] ~~Groups still using local storage/other groups feature bugs~~ Patched, seems to be working

- [x] ~~Unsupported image types may be uploaded~~ Patched with file validators.

# Acceptance criteria

- [ ] Upload large datasets or baselines that will take longer than the default timeout to ensure `gevent` class workers are the proper solution to timeout.

- [ ] Build competitions several times and ensure that the latest Bundle downloaded from the homepage matches the Bundle downloaded from the build page.

- [ ] Verify built competitions are able to download from home correctly without missing files

- [x] Verify that you are able to delete competItions from the homepage.

- [x] Verify sign-up/password-reset send you emails, and that you only have to click the link given to verify your account, versus being redirected to a separate page and clicking a button. 

- [ ] For each default dataset:
     - Set your competition to use it
     - Build your competition
     - Verify build success, and make sure the zip has the correct files

**Comment by madclam** [comment]
When I signed up, I got immediately logged in: I did not have to use the confirmation email: 
![image](https://user-images.githubusercontent.com/7594063/30506740-49d8ea28-9a33-11e7-9ee1-060d355dd213.png)

**Comment by madclam** [comment]
I uploaded a TIFF file as logo: I received no complaint, but then the logo did not get displayed.

**Comment by madclam** [comment]
Documentation pages: We still have the variables displayed with a $ sign in the rendering.
![image](https://user-images.githubusercontent.com/7594063/30506873-3f7c49f2-9a34-11e7-8084-0c36b0e84494.png)

Once we edit and save, then it's fine:

![image](https://user-images.githubusercontent.com/7594063/30506889-64145110-9a34-11e7-8ce6-c462bd886206.png)

**Comment by madclam** [comment]
I clicked on PROFILE and got an error
https://chalab.herokuapp.com/user/profile
![image](https://user-images.githubusercontent.com/7594063/30507122-42757190-9a36-11e7-9c94-393eabf1e713.png)

I tried it again after a big file upload was finished. Then it worked.

**Comment by madclam** [comment]
Download from front page works fine. Bundle tested on Codalab http://docker-server.lri.fr/competitions/1479.

Can you **add the FILE SIZE** so people know how big the download will be.
Thanks.

**Comment by madclam** [comment]
Large dataset upload is all fine (383 MB). I got an error because my zip file did not include a directory with the files in it:
Expected a single file/folder in path, got multiple: ['lothlorian_feat.name', 'lothlorian_test.data', 'lothlorian_label.name', 'lothlorian_train.solution', 'lothlorian_train.data', 'lothlorian_valid.data']

Would be nice to accept both a "flat" archive (not directory structure) and
lothlorian/
     lothlorian_feat.name
     lothlorian_test.data
     lothlorian_label.name
     lothlorian_train.solution
     lothlorian_train.data
     lothlorian_valid.data

**Comment by madclam** [comment]
Not sure what this is:
Build competitions several times and verify that the latest Bundle downloaded from the homepage matches the one in the bundler

**Comment by madclam** [comment]
I tried to create a "group" and this worked fine. BUT, I could not create a challenge using the template of that group.

![image](https://user-images.githubusercontent.com/7594063/30507382-f20da35a-9a38-11e7-9f11-52be4d77d793.png)

**Comment by madclam** [comment]
For each default dataset:

Set your competition to use it
Build your competition
Verify build success, and make sure the zip has the correct files

**I did not check for each dataset, but did it for one.**

**Comment by Tthomas63** [comment]
1) The debug logic has been re-done again. I just tested after clearing the database, and mandatory email confirmation is working at the time of writing this.

2) Documentation now auto-updates when viewing the page, these templates should automatically be rendered now.

3) The `profiles` too many connection error is specific to the staging environment. I'll make a script to reset connections when the branch pushes to Heroku.

```This occurs on Hobby Tier (hobby-dev and hobby-basic) plans, which have a max connection limit of 20 per user. To resolve this error, close some connections to your database by stopping background workers, reducing the number of dynos, or restarting your application in case it has created connection leaks over time. A discussion on handling connections in a Rails application can be found here.```

4) File size added to download button!

5) I have not started the `metadata` task, or the issues regarding the structure of datasets. This is next within my priorities along with kill bad tasks/restart bad tasks.

6) Groups should be working now! This was an issue with code still referencing local storage vs azure storage.

The staging server database has been reset and is ready for some more testing!

---- Screenshots ----

![screen shot 2017-09-19 at 12 20 29 pm](https://user-images.githubusercontent.com/28552312/30611033-067d1100-9d35-11e7-9b08-3bf05f5a1ea1.png)

**Comment by Tthomas63** [comment]
In order to hit the Chalab Sept release deadline, I think we'll need to review this probably by the end of the week.

**Comment by madclam** [comment]
Create datasets:
<img width="739" alt="screen shot 2017-09-26 at 5 47 16 pm" src="https://user-images.githubusercontent.com/7594063/30890677-31f32064-a2e3-11e7-9c69-8a321101ce23.png">
The adult dataset is found multiple times in the default menu.

**Comment by madclam** [comment]
It is still not possible to upload datasets without a directory structure:
![image](https://user-images.githubusercontent.com/7594063/30932952-f497262a-a37d-11e7-8ee1-437109563986.png)
I think we had an issue for that, I cannot find it.

**Comment by madclam** [comment]
Load large dataset:
https://www.dropbox.com/s/t1a83sfwj9cnq41/lothlorian.zip?dl=0
383 MB
![image](https://user-images.githubusercontent.com/7594063/30934682-262a5e28-a383-11e7-9166-3e2b16ed387e.png)
The second time I tried it worked but then I got this error:
![image](https://user-images.githubusercontent.com/7594063/30935292-10439686-a385-11e7-9a02-8d4e7b45b30f.png)
When in fact my dataset contained:
![image](https://user-images.githubusercontent.com/7594063/30935317-2772fb62-a385-11e7-8c7e-79e5acdfb2ac.png)
So what is missing is:
lothlorian_valid.solution and lothlorian_test.solution.
Also can we add a link to go back the previous page after we get this error message?

**Comment by madclam** [comment]
I uploaded
https://www.dropbox.com/s/q0ktl6p8sis1zt6/robert.zip?dl=0
and got again the error:
![image](https://user-images.githubusercontent.com/7594063/30935642-2bcb772e-a386-11e7-8d25-b6a98bbb09dc.png)
I tried twice.

**Comment by madclam** [comment]
I tried even smaller datasets:
https://www.dropbox.com/s/eqgspfawads2bc6/gina.zip?dl=0
dis not go through: only 19 MB
![image](https://user-images.githubusercontent.com/7594063/30992819-8b58985e-a460-11e7-8d77-9ef4522c5d1f.png)

So the heroku server cannot take anything. There is no point in continuing with it. Let's switch to Azure.

**Comment by madclam** [comment]
BTW
https://www.dropbox.com/s/eqgspfawads2bc6/gina.zip?dl=0
19 MB
uploaded fine on
https://chalab.lri.fr

**Comment by madclam** [comment]
However on 
https://chalab.lri.fr
https://www.dropbox.com/s/q0ktl6p8sis1zt6/robert.zip?dl=0
191 MB gave me the error:

![image](https://user-images.githubusercontent.com/7594063/30993403-ba3f5b8c-a463-11e7-84d8-c295530be9f9.png)

**Comment by Tthomas63** [comment]
Closing this for now. We have moved away from this branch and it's changes.
